loader prototype
ALI-KHALED-13/feedback-hub pull request #26
Opened 2023-05-04 12:06 UTC by ALI-KHALED-13

2023-05-05 13:59 UTC, Elena-Erganyan requested changes
I like how it looks, beautiful 😃 
Couple of comments, very small ones

2023-05-05 13:59 UTC, Elena-Erganyan commented on client/src/pages/Login/index.tsx
We can delete `isLoading` (line 61) because don't use it anymore

2023-05-05 13:59 UTC, Elena-Erganyan commented on client/src/pages/Register/index.tsx
Same, line 66, remove `isLoading`

2023-05-06 12:00 UTC, ALI-KHALED-13 commented on client/src/GlobalStyles.ts
> +    color-scheme: light dark;
so this seems to help to display the website correctly if a user has a "dark reader" extension turned on for our website, I noticed it works with my trivia game so transferred it here

2023-05-06 12:11 UTC, Elena-Erganyan approved these changes

2023-05-06 12:11 UTC, merged