Frontend dashboard
ALI-KHALED-13/feedback-hub pull request #37
Opened 2023-05-19 17:34 UTC by ALI-KHALED-13

2023-05-20 16:32 UTC, Elena-Erganyan requested changes
Great work Ali 👏 Really liked it, so many things were taken in account
It looks nice overall, some small comments UI wise are coming soon
Left some comments regarding your code, in general it's good :)

2023-05-20 16:32 UTC, Elena-Erganyan commented on client/src/components/BarChart/index.tsx
> +  data: ChartData<"bar", (number | [number, number] | null)[], string>/*{
To get rid of the TS error here add the following:
`import { ChartData } from "chart.js";`

2023-05-20 18:26 UTC, Elena-Erganyan commented
UI comments:
1) Common:
- there should be `max-width: 111rem` as on the other pages
- for consistency purposes would be nice to make border-radius for both blocks (`UserProfile` and `StyledContributionsArea`) 1rem
- a bit more of padding would look better (1.5 - 2rem for each block)
2) `UserProfile` part:
- icons of delete and upload image buttons are not centered vertically
- in my opinion it would be better to put email as the 3rd property (logically and because it can't be edited for now)
3) `StyledContributionsArea` part:
- to avoid the messiness in styling it's better to take colors for tabs from `GlobalStyles`
- also I think `Overview` tab also should have some highlighting color
- products are not clickable (there is no link to the product page there)
- feedback look like this:
![Screenshot_1](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/7e0d8d32-c267-499b-b184-c60731ace2c4)
so we can't see its borders
`box-shadow: 0 0 10px 1px #CFD7FF` would do it I guess :)
- on some mobile screens we have this (example: IPhone X)
![Screenshot_2](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/33dfb330-9a92-4cc2-9aab-1715b60d2070)
Having a scrollbar is okay, the problem is that the left tab is not fully shown
- there should be some gap between the products (feedback, comments)
![Screenshot_3](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/151e5e61-cd80-48af-87da-b6a24dce6621)

2023-05-21 09:30 UTC, ALI-KHALED-13 commented on client/src/redux/api/productsApi.ts
> +      providesTags: (_result, _error, arg)=> [{type: 'Products', id: `List_${arg.key}=${arg.value}`}],
thanks for pointing it out, I totally missed changing the invalidation part.. so imagine this scenario:
user going to dashboard - product tab, then adding a product and going back to that tab.. the data in that tab must be refetched (invalidated) to show the new product added

2023-05-21 09:37 UTC, ALI-KHALED-13 commented on client/src/redux/api/feedbackApi.ts
> +      providesTags: (_result, _error, arg)=> [{ type: 'Feedback', id: 'LIST' }],
wanted to talk about it

2023-05-21 09:38 UTC, ALI-KHALED-13 commented on client/src/pages/Dashboard/index.tsx
> +          <div>{getErrorMessage(activeQueryState.error) as string}</div>
I think displaying it here would be better

2023-05-21 09:40 UTC, ALI-KHALED-13 commented on client/src/components/UserProfile/index.tsx
> +    const fileInput = ev.target as HTMLInputElement;
thanks :)

2023-05-21 16:39 UTC, Elena-Erganyan approved these changes
Well done 😃

2023-05-21 16:41 UTC, merged