Frontend feedback form
ALI-KHALED-13/feedback-hub pull request #40
Opened 2023-05-25 22:31 UTC by ALI-KHALED-13

2023-05-26 16:03 UTC, ALI-KHALED-13 commented
test comment

2023-05-26 16:05 UTC, ALI-KHALED-13 commented
test

2023-05-28 10:53 UTC, Elena-Erganyan requested changes
The addition works, well done 😃 
Left some comments
More of review will be done once you finish with the rest part

2023-05-28 10:53 UTC, Elena-Erganyan commented on client/src/pages/FeedbackForm/index.tsx
> +          <Button color="violet" /* should it be product theme color? */ hoverColor="lightViolet">
I would say let's keep it simple, i.e. violet everywhere

2023-05-28 10:53 UTC, Elena-Erganyan commented on client/src/pages/FeedbackForm/index.tsx
> +const FeedbackForm =()=> {
I understand it's half baked for now (I can see many unused variables/imports). So I will check it thoroughly once you are done with editing and deleting as well.

2023-05-28 10:53 UTC, Elena-Erganyan commented on client/src/pages/FeedbackForm/index.tsx
> +        note="change feedback status"
Should look consistent. The note and the status should be capitalized
![Screenshot_1](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/8b55198a-331f-45ec-8aba-4565a8ae2edd)

2023-05-28 18:03 UTC, ALI-KHALED-13 commented on models/Product.js
> +        if (tagsArr.length < 3){
8?

2023-05-28 18:08 UTC, ALI-KHALED-13 commented on client/src/pages/ProductForm/index.tsx
> +      <TagInput
fixed.. thanks

2023-05-31 17:12 UTC, Elena-Erganyan requested changes
1) Logged in as @hoho, created a feedback on the `Feedback Hub` product. @hoho is neither an owner nor a contributor of a product. In theory @hoho should be able to edit his own feedback (except the status). However, when I tried to edit some info and save it the following error occurred:
![Screenshot_1](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/d0433083-5c19-479a-9dff-b276c7fa40d9)
2) Logged in as myself. I'm a contributor of the `Feedback Hub` product. I should be able to change only a status of any feedback. When I tried to do that and save the feedback I had this error
![Screenshot_2](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/8f9ec1f6-9f46-431a-8e54-85816d154766)
3) Logged in as @hoho and added a feedback to the `Test product` with the status "Planned" (I could do because @hoho is the owner of the product). When I tried to change the status it said:
![Screenshot_3](https://github.com/ALI-KHALED-13/feedback-hub/assets/22096337/66ce0c8c-64c8-4aeb-a6f3-5e8e275c65c7)

4) In all those cases if I try to edit and save again it's not saved and I don't see any error alert anymore.
5) When I deleted a feedback and refreshed the product page the alert message that the feedback was deleted still appeared (probably because of some info in history). Not a critical bug, low priority, can be ignored for now 😝

2023-05-31 17:12 UTC, Elena-Erganyan commented on client/src/pages/Dashboard/index.tsx
> +    <AlertMessage
Just a note: when I went through the link in the dashboard and deleted the feedback it redirected me to the product page, not to this one 🤔

2023-05-31 18:30 UTC, ALI-KHALED-13 commented
@Elena-Erganyan solved bugs number 1, 2 and hopefully 3 (forgot to test the later XD)
issue 4 is related to alertMessage again ;( .. I must look for a definite solution
issue 5 will be investigated too

2023-06-01 12:56 UTC, Elena-Erganyan approved these changes
Good job 👏

2023-06-01 14:25 UTC, merged