Frontend feedback page
ALI-KHALED-13/feedback-hub pull request #41
Opened 2023-05-27 12:07 UTC by Elena-Erganyan

2023-05-27 16:05 UTC, ALI-KHALED-13 requested changes
few comments

2023-05-27 16:05 UTC, ALI-KHALED-13 commented on client/src/redux/api/feedbackApi.ts
> +      providesTags: (_result, _error, arg)=> [{ type: 'Feedback', id: 'List' }],
this tag will be overridden by mine.. just saying

2023-05-27 16:05 UTC, ALI-KHALED-13 commented on client/src/components/Comment/index.tsx
> +      {isReplyFormShown &&
I believe this form can be unified with the from in FeedbackPage, all joined under 1 component?

2023-05-27 16:17 UTC, Elena-Erganyan commented on client/src/pages/FeedbackPage/index.tsx
> +        <StyledFeedbackPageWrapper>
Agreed, will fix it
I just used this component before refactoring in several places on the page, that's way made up so 'general' name

2023-05-28 15:56 UTC, ALI-KHALED-13 approved these changes
Well done :)

2023-05-28 15:56 UTC, merged