Backend
ALI-KHALED-13/feedback-hub pull request #6
Opened 2023-03-08 13:24 UTC by ALI-KHALED-13

2023-03-08 15:45 UTC, Elena-Erganyan requested changes

2023-03-08 15:45 UTC, Elena-Erganyan commented on api/feedback/controllers.js
> +        tag.save();
Add `await` please

2023-03-08 15:45 UTC, Elena-Erganyan commented on api/feedback/controllers.js
> +    targetProduct.save();
Await 😭

2023-03-08 15:45 UTC, Elena-Erganyan commented on api/feedback/controllers.js
> +  owner.save();
Await

2023-03-08 15:45 UTC, Elena-Erganyan commented on api/feedback/controllers.js
> +  res.status(200).json(`feedback was updated succefully`)
Change the comment to "deleted successfully" and check the status code

2023-03-21 15:58 UTC, Elena-Erganyan commented on server.js
> +app.use("/api/status", statusRoutes)
Better to use "statuses" maybe? For consistency :) 
Not a big deal though, we can keep it this way

2023-03-23 17:12 UTC, Elena-Erganyan requested changes
First of all, great job 👏
Very structured and neat work.
--------
I have left some comments here and there, please have a look :)

General comment to all controllers, where the `id` is used (get one item, modify, delete): 
If the `id` is not valid the error like this one will be thrown: `internal server Error: Cast to ObjectId failed for value \"640f363970dbd0a7d994710\" (type string) at path \"_id\" for model \"feedback\` (you can see it if you pass an id which is shorter than an usual one for example).
So for the sake of error handling probably it's better to check the `id` using `mongoose.Types.ObjectId.isValid(id)` and throw some custom error.

2023-03-23 18:35 UTC, ALI-KHALED-13 commented on api/comments/controllers.js
> +  if (parentFeedback) { // only if it exists (it might have been deleted)
added explicitly by the script that submits the comment made

2023-03-23 18:39 UTC, ALI-KHALED-13 commented on api/users/controllers/updateUser.js
> +
this can be a future change where we define access more tightly, but for now the current logic works

2023-03-23 18:55 UTC, Elena-Erganyan approved these changes

2023-03-23 18:56 UTC, merged